# Neuro-Relay Debug Configuration
debug:
  enabled: true
  trace:
    enabled: true
    verbose: false
    show_file_path: false
    show_timestamp: true
    max_value_len: 60
    max_locals: 4
    max_stack_depth: 12
    use_color: true
    include_paths:
      - "src/dev/nakurity"
      - "src/dev/tests"
    exclude_functions:
      - "write_log"
      - "trace"
      - "__enter__"
      - "__exit__"
      - "_notify_watchers"
    events:
      - "call"
      - "return" 
      - "exception"
      # - "line"  # Uncomment for very verbose line-by-line tracing
  logging:
    level: "INFO"
    file: "logs/neuro_relay_debug.log"
    console: true

relay:
  intermediary:
    host: "127.0.0.1"
    port: 8765
    max_connections: 50
  backend:
    timeout: 30
    retry_attempts: 3
  action_timeout: 60

performance:
  websocket:
    ping_interval: 20
    ping_timeout: 10
    max_message_size: 2097152  # 2MB